# src/main/resources/application.yml

server:
  servlet:
    context-path: /slomfin
    register-default-servlet: true
  tomcat:
    relaxed-query-chars: "|,{,},[,]"
  port: 8443
  ssl:
    bundle: slomfinbundle
    enabled: true

spring:
  ssl:
    bundle:
      jks:
        slomfinbundle:
          key:
            alias: tomcat17
          keystore:
            location: file:${KEYSTORE_LOCATION}/TomcatJava17.jks
            password: ${KEYSTORE_PASS}
            type: PKCS12

management:
  info:
    env:
      enabled: true
  endpoints:
    enabled-by-default: false
    jmx:
      exposure:
        exclude: "*"
    web:
      discovery:
        enabled: true
      exposure:
        include: "info,health,refresh"
  endpoint:
    info:
      enabled: true
    refresh:
      enabled: true
    health:
      enabled: true
